---
title: "UATX Quantitative Reasoning - Analysis"
---


This is the course homepage for UATX INF 1130 (Quantitative Reasoning I). All course materials can be found through this website, and information will be updated throughout the term. This site is designed for students, but visitors are welcome. General information for visitors is available via the [About page](about.qmd).

A typical class week consists of one or two of the topics from [the textbook](https://dtkaplan.github.io/QR-A/) and includes textbook readings, homework questions, and a short weekly quiz.

## Professors

| Professor | Email Address | Office Hours |
|-----------|---------------|--------------|
| Prof. David Ruth | druth@uaustin.org | Wednesday 11:15-12:45; otherwise by appointment |
| Asst. Prof. Dorothy Dickmann | ddickmann@uaustin.org | Thursday 09:30-11:30; otherwise by appointment. Scarbrough second floor — email for access. |

## Class Meetings

| Section | Meeting Time | Classroom | Professor |
| ------- | ------------ | --------- | --------- |
| 001 | Monday/Wednesday 10:00-11:15 | Scarbrough 311 | Prof. David Ruth |
| 003 | Tuesday/Thursday 11:30-12:45 | Scarbrough 312 | Asst. Prof. Dorothy Dickmann |
| 004 | Tuesday/Thursday 14:00-15:15 | Scarbrough 313 | Asst. Prof. Dorothy Dickmann |

<!--Topics: 

i. Modeling, the broad framework for quantitative reasoning
i. Quantities and dimensions
i. Rates and their uses
i. Magnitudes for representing the very big along side the very small
i. Function building blocks. Functions are the links between quantities in our models.
i. Uncertain quantities. Functions also provide a way to represent uncertainty.
i. Custom design of functions, to power the models we build
i. Hypothesis and likelihood, to connect data to models and conclusion
i. Bayesian reasoning, updating our beliefs based on evidence
i. Dynamics, the study of systems that change in time
i. Rates of change, a revolution in quantitative thinking
i. Accumulation, the flip side of rates of change
-->